// <auto-generated />
using JobBoardAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBoardAPI.Migrations
{
    [DbContext(typeof(JobOffertsDbContext))]
    [Migration("20240222134116_RequirementChanges")]
    partial class RequirementChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobBoardAPI.Entities.JobOffert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobTime")
                        .HasColumnType("int");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("JobOfferts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "TrustFormulaIt",
                            Description = "Job offer for C# developer with minimum 3 years experience and graduated",
                            JobTime = 1,
                            JobType = 1,
                            Location = "Warsaw",
                            Salary = 2500.0,
                            Title = "Software developer"
                        });
                });

            modelBuilder.Entity("JobBoardAPI.Entities.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("JobOffertId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobOffertId")
                        .IsUnique();

                    b.ToTable("Requirements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Education = 0,
                            Experience = 3,
                            JobOffertId = 1
                        });
                });

            modelBuilder.Entity("JobBoardAPI.Entities.Seeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Seekers");
                });

            modelBuilder.Entity("JobOffertSeeker", b =>
                {
                    b.Property<int>("JobOffertsId")
                        .HasColumnType("int");

                    b.Property<int>("SeekersId")
                        .HasColumnType("int");

                    b.HasKey("JobOffertsId", "SeekersId");

                    b.HasIndex("SeekersId");

                    b.ToTable("OffertsSeekers", (string)null);
                });

            modelBuilder.Entity("JobBoardAPI.Entities.Requirement", b =>
                {
                    b.HasOne("JobBoardAPI.Entities.JobOffert", null)
                        .WithOne("Requirement")
                        .HasForeignKey("JobBoardAPI.Entities.Requirement", "JobOffertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobOffertSeeker", b =>
                {
                    b.HasOne("JobBoardAPI.Entities.JobOffert", null)
                        .WithMany()
                        .HasForeignKey("JobOffertsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBoardAPI.Entities.Seeker", null)
                        .WithMany()
                        .HasForeignKey("SeekersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobBoardAPI.Entities.JobOffert", b =>
                {
                    b.Navigation("Requirement")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
